name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --build-arg NO_PROXY="artifactory.dhl.com,localhost,127.0.0.1" -t my-app .

      - name: Run Container
        run: |
          docker run --rm my-app env | grep NO_PROXY
